const data = [
  {
    id: 1,
    graduationYear: 2566,
    studentId: "64010001",
    fullName: "นายสมชาย ใจดี",
    currentOccupation: "Software Developer",
  },
  {
    id: 2,
    graduationYear: 2566,
    studentId: "64010002",
    fullName: "นางสาวพรทิพย์ ศรีสุข",
    currentOccupation: "Digital Marketing Specialist",
  },
  {
    id: 3,
    graduationYear: 2566,
    studentId: "64010003",
    fullName: "นายธนวัฒน์ แสงทอง",
    currentOccupation: "Backend Developer",
  },
  {
    id: 4,
    graduationYear: 2566,
    studentId: "64010004",
    fullName: "นางสาวอรทัย จันทร์เพ็ญ",
    currentOccupation: "QA Engineer",
  },
  {
    id: 5,
    graduationYear: 2566,
    studentId: "64010005",
    fullName: "นายวรพล คำดี",
    currentOccupation: "Frontend Developer",
  },
  {
    id: 6,
    graduationYear: 2566,
    studentId: "64010006",
    fullName: "นางสาวกมลชนก สุขใจ",
    currentOccupation: "UX Designer",
  },
  {
    id: 7,
    graduationYear: 2566,
    studentId: "64010007",
    fullName: "นายปฐวี ศรีทอง",
    currentOccupation: "DevOps Engineer",
  },
  {
    id: 8,
    graduationYear: 2566,
    studentId: "64010008",
    fullName: "นางสาวชลธิชา แสงฟ้า",
    currentOccupation: "Product Designer",
  },
  {
    id: 9,
    graduationYear: 2566,
    studentId: "64010009",
    fullName: "นายเอกชัย พูนผล",
    currentOccupation: "System Analyst",
  },
  {
    id: 10,
    graduationYear: 2566,
    studentId: "64010010",
    fullName: "นางสาวรัตนา ใจเย็น",
    currentOccupation: "Business Analyst",
  },

  {
    id: 11,
    graduationYear: 2565,
    studentId: "63020001",
    fullName: "นางสาวสุพัตรา แก้วใส",
    currentOccupation: "UI/UX Designer",
  },
  {
    id: 12,
    graduationYear: 2565,
    studentId: "63020002",
    fullName: "นายอนุชิต วัฒนชัย",
    currentOccupation: "Data Analyst",
  },
  {
    id: 13,
    graduationYear: 2565,
    studentId: "63020003",
    fullName: "นางสาวจิราภรณ์ ทองดี",
    currentOccupation: "Frontend Developer",
  },
  {
    id: 14,
    graduationYear: 2565,
    studentId: "63020004",
    fullName: "นายกิตติศักดิ์ พูนผล",
    currentOccupation: "System Analyst",
  },
  {
    id: 15,
    graduationYear: 2565,
    studentId: "63020005",
    fullName: "นายณัฐวุฒิ แก้วคำ",
    currentOccupation: "Cloud Engineer",
  },
  {
    id: 16,
    graduationYear: 2565,
    studentId: "63020006",
    fullName: "นางสาวอัญชลี ศรีสุข",
    currentOccupation: "QA Automation",
  },
  {
    id: 17,
    graduationYear: 2565,
    studentId: "63020007",
    fullName: "นายภาคิน วัฒนา",
    currentOccupation: "Mobile Developer",
  },
  {
    id: 18,
    graduationYear: 2565,
    studentId: "63020008",
    fullName: "นางสาวเบญจพร แสงทอง",
    currentOccupation: "SEO Specialist",
  },
  {
    id: 19,
    graduationYear: 2565,
    studentId: "63020009",
    fullName: "นายจักรินทร์ บุญช่วย",
    currentOccupation: "IT Consultant",
  },
  {
    id: 20,
    graduationYear: 2565,
    studentId: "63020010",
    fullName: "นางสาวปวีณา คำแพง",
    currentOccupation: "Project Coordinator",
  },

  {
    id: 21,
    graduationYear: 2564,
    studentId: "62030001",
    fullName: "นายอนุชา วัฒนชัย",
    currentOccupation: "Data Scientist",
  },
  {
    id: 22,
    graduationYear: 2564,
    studentId: "62030002",
    fullName: "นางสาวพิมพ์ชนก สายใจ",
    currentOccupation: "Product Owner",
  },
  {
    id: 23,
    graduationYear: 2564,
    studentId: "62030003",
    fullName: "นายศุภกร รุ่งเรือง",
    currentOccupation: "Mobile Developer",
  },
  {
    id: 24,
    graduationYear: 2564,
    studentId: "62030004",
    fullName: "นางสาวกัญญารัตน์ นาคดี",
    currentOccupation: "Business Analyst",
  },
  {
    id: 25,
    graduationYear: 2564,
    studentId: "62030005",
    fullName: "นายชาญชัย ใจกล้า",
    currentOccupation: "IT Support",
  },
  {
    id: 26,
    graduationYear: 2564,
    studentId: "62030006",
    fullName: "นางสาวนฤมล พูนสุข",
    currentOccupation: "HR Specialist",
  },
  {
    id: 27,
    graduationYear: 2564,
    studentId: "62030007",
    fullName: "นายพิชิต แสงเงิน",
    currentOccupation: "Network Engineer",
  },
  {
    id: 28,
    graduationYear: 2564,
    studentId: "62030008",
    fullName: "นางสาวณิชา สุขสันต์",
    currentOccupation: "Scrum Master",
  },
  {
    id: 29,
    graduationYear: 2564,
    studentId: "62030009",
    fullName: "นายวสุ พลอยดี",
    currentOccupation: "System Engineer",
  },
  {
    id: 30,
    graduationYear: 2564,
    studentId: "62030010",
    fullName: "นางสาวปิยะดา แก้วทอง",
    currentOccupation: "Project Manager",
  },

  {
    id: 31,
    graduationYear: 2563,
    studentId: "61040001",
    fullName: "นายธนกร ปัญญา",
    currentOccupation: "Business Owner",
  },
  {
    id: 32,
    graduationYear: 2563,
    studentId: "61040002",
    fullName: "นางสาวศิริพร แก้วมณี",
    currentOccupation: "HR Specialist",
  },
  {
    id: 33,
    graduationYear: 2563,
    studentId: "61040003",
    fullName: "นายปณชัย วรากร",
    currentOccupation: "IT Support",
  },
  {
    id: 34,
    graduationYear: 2563,
    studentId: "61040004",
    fullName: "นายณัฐพล แสงดี",
    currentOccupation: "Sales Engineer",
  },
  {
    id: 35,
    graduationYear: 2563,
    studentId: "61040005",
    fullName: "นางสาวพัชรี ใจมั่น",
    currentOccupation: "Marketing Executive",
  },
  {
    id: 36,
    graduationYear: 2563,
    studentId: "61040006",
    fullName: "นายชัยวัฒน์ ศรีทอง",
    currentOccupation: "IT Consultant",
  },
  {
    id: 37,
    graduationYear: 2563,
    studentId: "61040007",
    fullName: "นางสาวอารีย์ แสงสว่าง",
    currentOccupation: "Content Creator",
  },
  {
    id: 38,
    graduationYear: 2563,
    studentId: "61040008",
    fullName: "นายสุริยะ กล้าหาญ",
    currentOccupation: "Network Technician",
  },
  {
    id: 39,
    graduationYear: 2563,
    studentId: "61040009",
    fullName: "นางสาวกุลธิดา ทองสุข",
    currentOccupation: "Office Administrator",
  },
  {
    id: 40,
    graduationYear: 2563,
    studentId: "61040010",
    fullName: "นายอภิวัฒน์ นาคทอง",
    currentOccupation: "Operations Manager",
  },

  {
    id: 41,
    graduationYear: 2562,
    studentId: "60050001",
    fullName: "นายวีรชัย กล้าหาญ",
    currentOccupation: "Network Engineer",
  },
  {
    id: 42,
    graduationYear: 2562,
    studentId: "60050002",
    fullName: "นางสาวณัฐธิดา ชัยศรี",
    currentOccupation: "Project Manager",
  },
  {
    id: 43,
    graduationYear: 2562,
    studentId: "60050003",
    fullName: "นายภัทรพล แสงดาว",
    currentOccupation: "DevOps Engineer",
  },
  {
    id: 44,
    graduationYear: 2562,
    studentId: "60050004",
    fullName: "นายชัยณรงค์ ใจดี",
    currentOccupation: "System Administrator",
  },
  {
    id: 45,
    graduationYear: 2562,
    studentId: "60050005",
    fullName: "นางสาวกมลพร พูนสุข",
    currentOccupation: "QA Engineer",
  },
  {
    id: 46,
    graduationYear: 2562,
    studentId: "60050006",
    fullName: "นายวรวิทย์ แก้วทอง",
    currentOccupation: "Security Analyst",
  },
  {
    id: 47,
    graduationYear: 2562,
    studentId: "60050007",
    fullName: "นางสาวเบญญาภา ศรีทอง",
    currentOccupation: "UX Researcher",
  },
  {
    id: 48,
    graduationYear: 2562,
    studentId: "60050008",
    fullName: "นายศุภชัย แสงดี",
    currentOccupation: "Technical Support",
  },
  {
    id: 49,
    graduationYear: 2562,
    studentId: "60050009",
    fullName: "นางสาววาสนา คำดี",
    currentOccupation: "Account Executive",
  },
  {
    id: 50,
    graduationYear: 2562,
    studentId: "60050010",
    fullName: "นายธีรพงษ์ ใจกล้า",
    currentOccupation: "IT Auditor",
  },
  {
    id: 51,
    graduationYear: 2566,
    studentId: "59060001",
    fullName: "นางสาวสุดารัตน์ แก้วใส",
    currentOccupation: "Digital Strategist",
  },
  {
    id: 52,
    graduationYear: 2566,
    studentId: "59060002",
    fullName: "นายกฤษฎา วัฒนชัย",
    currentOccupation: "Full Stack Developer",
  },
];

export default data;
